<?php
// AIPenScan credential setup. Populates config.local.php (gitignored, 0600)
// from environment variables, e.g. with a secret injected from the store:
//
//   OPENAI_KEY=... php scripts/setup.php store OPENAI_KEY api_key
//   php scripts/setup.php check        # verify key + list available models
//   php scripts/setup.php show         # show current config (key masked)
declare(strict_types=1);

require_once __DIR__ . '/../lib/Config.php';
require_once __DIR__ . '/../lib/AiClient.php';

$cmd = $argv[1] ?? 'help';

if ($cmd === 'store') {
  $envVar = $argv[2] ?? '';
  $cfgKey = $argv[3] ?? '';
  if ($envVar === '' || $cfgKey === '') {
    fwrite(STDERR, "usage: php scripts/setup.php store <ENV_VAR> <config_key>\n");
    exit(2);
  }
  $val = getenv($envVar);
  if ($val === false || trim($val) === '') {
    fwrite(STDERR, "env var $envVar is empty or missing\n");
    exit(1);
  }
  $root = dirname(__DIR__);
  $file = $root . '/config.local.php';
  $cur = is_file($file) ? (require $file) : [];
  if (!is_array($cur)) $cur = [];
  $cur[$cfgKey] = trim($val);
  file_put_contents($file, "<?php\n// AIPenScan local secrets. DO NOT COMMIT. Generated by scripts/setup.php.\nreturn " . var_export($cur, true) . ";\n");
  chmod($file, 0600);
  echo "stored $cfgKey from \$$envVar into config.local.php\n";
  exit(0);
}

if ($cmd === 'check') {
  $cfg = new Config(dirname(__DIR__));
  $key = (string)$cfg->get('api_key');
  if ($key === '') {
    fwrite(STDERR, "no api_key configured. Run: php scripts/setup.php store <ENV_VAR> api_key\n");
    exit(1);
  }
  $ai = new AiClient($key, (string)$cfg->get('base_url'), 30);
  $models = $ai->listModels();
  echo 'OK, ' . count($models) . " models available:\n";
  foreach (array_slice($models, 0, 40) as $m) echo "  $m\n";
  exit(0);
}

if ($cmd === 'show') {
  $cfg = new Config(dirname(__DIR__));
  foreach ($cfg->all() as $k => $v) echo str_pad($k, 24) . $v . "\n";
  exit(0);
}

echo "usage:\n";
echo "  php scripts/setup.php store <ENV_VAR> <config_key>   store a credential\n";
echo "  php scripts/setup.php check                          verify key, list models\n";
echo "  php scripts/setup.php show                           show config (key masked)\n";
exit($cmd === 'help' ? 0 : 2);
